### ISSUE TITLE
1.1.0 release not compatible with older versions of Node

### ISSUE THREAD

**Issue by martinheidegger** [baygeldin/fullwidth#4]
`codePointAt` and `String.fromCodePoint` are methods were introduced with Node 4. Unfortunately many have still to use <= Node 0.12 _(like me)_. It would be awesome if `charCodeAt` could be used instead.

**Comment by baygeldin** [comment]
Well, since tests are passing anyway, it's true that there's actually no need for `codePointAt`. I changed it back and released a new version :)
