### ISSUE TITLE
Combining special characters in japanese:

### ISSUE THREAD

**Issue by martinheidegger** [baygeldin/fullwidth#5]
In japanese we have the half-width character `ﾟ` and `ﾞ`. Those transform the characters beforehand:
i.e. `ﾎﾟ` or `ﾄﾞ`

Those characters when run through `fullwidth` will stay two characters `ト゛` and `ホ゜` but it would be awesome if the characters would be transformed in the appropriate full-width character representation `ド` and `ポ`.

**Comment by baygeldin** [comment]
Hi, is it specific for `ﾎﾟ` and `ﾄﾞ` or are there other similar cases?

**Comment by martinheidegger** [comment]
A set of character has [Dakuten](https://en.wikipedia.org/wiki/Dakuten) support. I think [a hiragana character list](http://learnthekana.com/the-hiragana-chart/) usually shows all occurences.

**Comment by baygeldin** [comment]
I hope I understood your request correctly since I don't know much about Japanese language. Check out the 1.2.0 release :)

**Comment by martinheidegger** [comment]
Looks awesome, thanks!
